### ISSUE TITLE
по поводу тестового задания

### ISSUE THREAD

**Issue by oxxxxxy** [Voiislav/sgs#1]
Здарова, чел, я тож попавс в на эту же вакансию.

Чо, крч, пишу тебе с целью поинтересоваться, чо и как было. Надеюсь, что ответишь.

Так вот, чо и как было, как прошло? Прост гит посмотрели и _что было дальше_?

**Comment by Voiislav** [comment]
> Здарова, чел, я тож попавс в на эту же вакансию.
> 
> Чо, крч, пишу тебе с целью поинтересоваться, чо и как было. Надеюсь, что ответишь.
> 
> Так вот, чо и как было, как прошло? Прост гит посмотрели и _что было дальше_?

Привет, отписали, что результаты на рассмотрении и больше никаких новостей пока

**Comment by oxxxxxy** [comment]
Балииииииин, пон, спасибо за оперативность. 😉

**Comment by oxxxxxy** [comment]
Чутка инфы по срокам нашел, а ты закрыл. Ответ что ли получил?

> Привет, после тестового задания отвечают примерно в течение недели, если успешно, назначают собес на ближайшее время. Собес один, после него довольно долго ждал обратной связи, недели две.

**Comment by Voiislav** [comment]
> Чутка инфы по срокам нашел, а ты закрыл. Ответ что ли получил?
> 
> 
> 
> > Привет, после тестового задания отвечают примерно в течение недели, если успешно, назначают собес на ближайшее время. Собес один, после него довольно долго ждал обратной связи, недели две.
> 
> 
> 
> 

Привет, понял, спасибо)

**Comment by oxxxxxy** [comment]
Салам плотный, чо, с тобой на связь выходили?

**Comment by Voiislav** [comment]
> Салам плотный, чо, с тобой на связь выходили?

Привет, нет

**Comment by oxxxxxy** [comment]
Ну, шо, как дела? Связывались? А то вакансия в архив улетела.
Если тя взяли, то рад за тебя, потом, мб, опытом поделишься чутка.
